version: '2.1'
orbs:
  snyk: snyk/snyk@1.2.3
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: npm ci
      - snyk/scan: 
          monitor-on-build: true
workflows: null
